version: '3.7'
services:
  dynamodb-local:
    image: amazon/dynamodb-local:latest
    container_name: dynamodb-local
    ports:
      - "8000:8000"
    working_dir: /home/dynamodblocal
    command: '-jar DynamoDBLocal.jar -sharedDb -dbPath .'
  dynamodb-setup:
    depends_on:
      - dynamodb-local
    image: banst/awscli
    container_name: dynamodb-setup
    environment:
      AWS_ACCESS_KEY_ID: 'DUMMYIDEXAMPLE'
      AWS_SECRET_ACCESS_KEY: 'DUMMYEXAMPLEKEY'
    command: >
      dynamodb create-table --endpoint-url http://dynamodb-local:8000 --region ap-southeast-2
        --table-name books
        --attribute-definitions AttributeName=id,AttributeType=S
        --key-schema AttributeName=id,KeyType=HASH
        --provisioned-throughput ReadCapacityUnits=100,WriteCapacityUnits=100
